assets/js/overflowing-navbar.min.js, functions.php, lib/header.php, lib/nav.php, lib/scripts.php
Added LOGO/Site Title to header. Repositioned primary navigation.
=> Header and Nav changes

functions.php, lib/footer.php
The 'designed' version of the search tray is in search-tray.php
=> Remove extra search form; Fix default footer image filename

assets/scss/uams-supporting/uams-modules/side-by-side.scss, blocks/image-side-by-side.php
I figured out how to only use the picture element to achieve the visual placement. Now the browser _only_ loads the required image.
=> Move all Side-by-Side images into Picture element

acf_fields/news.php, blocks/news.php, lib/modules.php
=> Add Title Section for News

blocks/action-bar.php, blocks/call-out.php, blocks/cta.php, blocks/hero.php, blocks/news.php, blocks/overlay.php, blocks/post-category-tile.php, blocks/post-category-tiles.php, blocks/stacked.php
=> Add align class and additional class

assets/scss/uams-supporting/doctors-item.scss, assets/scss/uams-supporting/doctors-list.scss, assets/scss/uams-supporting/locations-item.scss
=> Add unit to flex shorthand

lib/header.php
https://uamsweb.atlassian.net/browse/UW20-65
=> UW20-65 Change aria-controls value for search toggler

assets/scss/uams-supporting/layout.scss, assets/scss/uams-supporting/template-default.scss
https://uamsweb.atlassian.net/browse/FD20-161
=> FD20-161 Styles to support matching AoE section root to default template

assets/scss/uams-supporting/layout.scss, assets/scss/uams-supporting/mixins.scss, assets/scss/uams-supporting/mixins/background-variant.scss, assets/scss/uams-supporting/utilities.scss, assets/scss/uams-supporting/utilities/background.scss, assets/scss/uams-supporting/variables.scss
- Styles for map legend
- More widespread styles, controlling text/link colors inside elements with the bg-* class for theme colors
=> FD20-148 add parking map to location page

assets/scss/uams-supporting/layout.scss
https://uamsweb.atlassian.net/browse/FD20-155
=> FD20-155 Add featured video field for AoE, Conditions, Treatments

assets/scss/style.scss, assets/scss/uams-supporting/text-callouts.scss, assets/scss/uams-supporting/variables.scss
https://uamsweb.atlassian.net/browse/FD20-120
=> FD20-120 adjust layout of alternate names

search.php
https://uamsweb.atlassian.net/browse/FD20-145
=> FD20-145 move physicians to below posts/pages in site search

assets/scss/uams-supporting/conditions-treatments.scss
https://uamsweb.atlassian.net/browse/FD20-179
=> Remove top margin if list container is after a list legend

assets/scss/uams-supporting/layout.scss
https://uamsweb.atlassian.net/browse/FD20-180
=> FD20-180 clean up container classes and styles

assets/scss/uams-supporting/doctors-item.scss, assets/scss/uams-supporting/layout.scss, assets/scss/uams-supporting/type.scss, assets/scss/uams-supporting/variables.scss
https://uamsweb.atlassian.net/browse/FD20-181
=> FD20-181 change physician's academic section layout on large viewports

blocks/hero.php, blocks/post-category-tile.php, blocks/post-category-tiles.php, blocks/stacked.php
https://uamsweb.atlassian.net/browse/FD20-186
=> Fd20 186 width of retina images oversized on retina display

assets/scss/style.scss, assets/scss/uams-supporting/doctors-cards.scss, assets/scss/uams-supporting/layout.scss, assets/scss/uams-supporting/variables.scss
https://uamsweb.atlassian.net/browse/FD20-188
=> Fd20-188 set container width of doctor cards container to prevent orphans

functions.php, html/header-2.html, html/header.html, html/module-examples.html, html/module_graphic-title.html, lib/footer.php
https://uamsweb.atlassian.net/browse/UW20-79
=> UW20-79 Accessibility issues

assets/scss/uams-supporting/buttons.scss, assets/scss/uams-supporting/doctors-item.scss, assets/scss/uams-supporting/layout.scss, assets/scss/uams-supporting/locations-list.scss
https://uamsweb.atlassian.net/browse/FD20-216
Be sure to Gulp CSS after merge
=> Fd20 216 multi line elements exceed bounds of card body in ie11

assets/scss/uams-supporting/links-tel.scss
https://uamsweb.atlassian.net/browse/FD20-213
=> Comment out styles that suppress tel link behavior on non-mobile

functions.php
https://uamsweb.atlassian.net/browse/UW20-89
https://make.wordpress.org/core/2019/10/09/introducing-handling-of-big-images-in-wordpress-5-3/
=> Disable the big image threshold

blocks/image-side-by-side.php
https://uamsweb.atlassian.net/browse/UW20-91
=> UW20-91 Side-by-Side image position

assets/scss/uams-supporting/layout.scss, assets/scss/uams-supporting/uams-modules/link-list.scss, functions.php, lib/page.php
https://uamsweb.atlassian.net/browse/UW20-75
=> UW20-92 display child pages

assets/scss/uams-supporting/uams-modules/side-by-side.scss
https://uamsweb.atlassian.net/browse/FD20-243
=> FD20-243 Adjust layout of side-by-side's link list on mobile

assets/scss/uams-supporting/doctors-list.scss
Setting styles to accommodate new aria-selected attribute structure
=> Adjust styles for a-z selector on condition/treatment archive

functions.php
https://uamsweb.atlassian.net/browse/UW20-96
=> add sr-only text and correct typo

.gitignore, lib/footer.php
https://uamsweb.atlassian.net/browse/FD20-263
=> Fd20-263 fix html validation errors on provider pages

functions.php, lib/footer.php, lib/header.php, lib/meta-box.php
https://uamsweb.atlassian.net/browse/UW20-132
=> UW20-132 multisite header behavior

acf_fields/cta.php, assets/scss/uams-supporting/uams-modules/cta-bar.scss
https://uamsweb.atlassian.net/browse/UW20-151
This set of changes was overwritten by a merge from master to dev.
=> UW20-151 add fatter option for cta bar padding redux

assets/scss/uams-supporting/uams-modules.scss
https://uamsweb.atlassian.net/browse/UW20-153
=> UW20-153 Adjust uams-module margins in landing page template

lib/footer.php
=> Hot Fix - Update DDEI facebook URL and add twitter

assets/scss/uams-supporting/type.scss
https://uamsweb.atlassian.net/browse/UW20-156
=> UW20-156 - Create ordered list style classes

assets/scss/style.scss, assets/scss/uams-supporting/tables.scss
https://uamsweb.atlassian.net/browse/UW20-161
=> UW20-161 set wordpress tables to use bootstrap table styles

blocks/hero.php
https://uamsweb.atlassian.net/browse/UW20-179
=> UW20-179 Hero block's align class not added to outermost container

lib/footer.php
This task is ready for the next release
https://uamsweb.atlassian.net/browse/UW20-178
=> UW20-178 Add ENT instagram

assets/scss/uams-supporting/template-default.scss
https://uamsweb.atlassian.net/browse/UW20-184
=> UW20-184 Extend default template styles to LearnDash

assets/scss/uams-supporting/template-default.scss
Ready for next release
https://uamsweb.atlassian.net/browse/UW20-198
=> UW20-198 Adjust image alignment styles

search.php
Ready for next release
https://uamsweb.atlassian.net/browse/UW20-200
=> UW20-200 Excerpts not displaying in site search

search.php
Ready for next release
https://uamsweb.atlassian.net/browse/FD20-381
=> FD20-381 UAMSHealth's site search returns conditions/treatments with no section heading

functions.php
https://uamsweb.atlassian.net/browse/UW20-202
=> UW20-202 Password Reset on uams-login

functions.php, html/html_template/index.html, html/html_template/landing-page/index.html, html/html_template/sample-page/index.html, html/html_template/sample-page/page-with-cover/index.html, html/html_template/sample-page/page-with-cover/test-child/index.html, html/html_template/sample-page/page-with-hero-header/index.html, html/html_template/subsite-header.html, lib/footer.php, lib/quicklinks.php
https://uamsweb.atlassian.net/browse/UW20-206
=> UW20-206 http in breadcrumbs home link

assets/scss/uams-supporting/cta-bar.scss, assets/scss/uams-supporting/layout.scss, assets/scss/uams-supporting/mixins/type.scss, assets/scss/uams-supporting/sidebar.scss, assets/scss/uams-supporting/type.scss, assets/scss/uams-supporting/uams-modules/graphic-title.scss, assets/scss/uams-supporting/uams-modules/landing-page-title.scss, assets/scss/uams-supporting/uams-modules/syndication/headlines.scss, assets/scss/uams-supporting/variables.scss, lib/header.php
https://uamsweb.atlassian.net/browse/UW20-229
The Find-a-Doc plugin need an expansion of some of the things in the theme, but that weren't specific to the Find-a-Doc plugin.
=> UW20-229 Create Styles to Support MyChart Open Scheduling

lib/footer.php
https://uamsweb.atlassian.net/browse/UW20-227
=> UW20-227 Set College of Health Professions Twitter Link in Footer

assets/scss/uams-supporting/uams-modules.scss, functions.php
https://uamsweb.atlassian.net/browse/FD20-600
=> FD20-600 & UW20-232 Logo List plugin

lib/extras.php
https://uamsweb.atlassian.net/browse/FD20-1378
=> [FD20-1378] Find-a-Doc Meta Values Pulling Individual Post Title

blocks/stacked.php
https://uamsweb.atlassian.net/browse/FD20-1534
Just code refactoring
=> [FD20-1534] Rebuild Stacked Image & Text and News Syndication Card Layout

functions.php, lib/scripts.php
https://uamsweb.atlassian.net/browse/FD20-2342
=> [FD20-2342] Set up constant for UAMS 2020 theme version

assets/scss/uams-supporting/template-default.scss
https://uamsweb.atlassian.net/browse/FD20-2595
=> [FD20-2595] Align Wide issue for YT videos in Gutenberg

blocks/section.php
https://uamsweb.atlassian.net/browse/FD20-2675
This is ready for the next release.
=> [FD20-2675] Add image, shortcode, table and file to whitelist

assets/scss/uams-supporting/layout.scss
https://uamsweb.atlassian.net/browse/FD20-2665
=> [FD20-2665] Add clear utility classes

assets/scss/uams-supporting/template-default.scss
https://uamsweb.atlassian.net/browse/FD20-2665
Adjusting behavior of first- and last-child elements
=> [FD20-2665] Add Class to Clear Floats

blocks/gallery.php, blocks/stacked.php
https://uamsweb.atlassian.net/browse/FD20-2704
=> [FD20-2704] Button Color in Stacked Image & Text Block with Auto Background

lib/footer.php
https://uamsweb.atlassian.net/browse/FD20-3127
* Fixed a bug with the $site variable value
* Updated destination of Terms of Use link
* Set legal links to open in new window
* Updated URL structure of the social media links
* Removed redundant social media link variable definitions
=> [FD20-3127] privacy links in footer

lib/footer.php
Ready for next release
https://uamsweb.atlassian.net/browse/FD20-3127
=> [FD20-3127] Update Health Footer

blocks/counter.php
Ready for the next release
https://uamsweb.atlassian.net/browse/FD20-1578
=> [FD20-1578] Counter Block returns NaN in Safari

lib/meta-box.php, lib/modules/class-wp-bootstrap-pagewalker.php
Ready for the next release
https://uamsweb.atlassian.net/browse/FD20-1549
=> [FD20-1549] Alternate Name for Automatic Menus

blocks/section.php
- Shortcode
- Gravity Forms
- Formidable
=> Add additional items to whitelist

blocks/hero.php
https://uamsweb.atlassian.net/browse/FD20-1579
=> [FD20-1579] Disabling Hero slide results in unexpected behavior

lib/nav.php
https://uamsweb.atlassian.net/browse/FD20-2950
- Remove page_on_front from exclude list
- Use exclude_tree instead of exclude
=> [FD20-2950] Hiding a page from auto menus result in descendants displaying on auto menu

lib/footer.php
https://uamsweb.atlassian.net/browse/FD20-3886
=> [FD20-3881; FD20-3886] Add "Price Transparency" link to the UAMSHealth.com footer

lib/nav.php
This is ready for the next release.
https://uamsweb.atlassian.net/browse/FD20-3283
=> [FD20-3283] Website Front Page is displaying in auto menus

lib/media-credit.php
This is basically just me doing code refactoring and adding comment documentation in lib/media-credit.php.
The only significant change I made here is the commenting out of the **uamswp_add_media_credit** function for housekeeping.
=> [FD20-4028] BUG - Wordpress Error - Block type core/image is already registered

functions.php
https://uamsweb.atlassian.net/browse/FD20-4035
=> [FD20-4035] Fix typo in name of option to retrieve

lib/quicklinks.php
https://uamsweb.atlassian.net/browse/FD20-4032
* Lots of code refactoring while I was in there
* The main thing is the commenting out of the instances of add_action for quick links
=> [FD20-4032] register_rest_route called incorrectly for quick links

lib/page.php
https://uamsweb.atlassian.net/browse/FD20-1573
=> [FD20-1573] Automatic Subpages Menu appearing in site search page results

functions.php
core/block
core/html
core/preformatted
core/rss
core/table
formidable/simple-form
formidable/simple-view
minervakb/faq
minervakb/search
minervakb/topic
minervakb/topics
wpseopress/faq-block
=> Roll back unregistration of blocks
